print("Agregar 5 Ejemplos con otras funciones no vistas en la sesión")
palabra="Hola mundo"
print("Frase original: ", palabra)
print("Función isupper():")
print(f"¿'{palabra}' está toda en mayúsculas?: {palabra.isupper()}")
print("\n2. Función zfill(15):")
print(f"Original: '{palabra}' | Con zfill: '{palabra.zfill(15)}'")
print("\n3. Función isspace():")
print(f"¿'{palabra}' contiene solo espacios? → {palabra.isspace()}")
print("\n4. Función removeprefix('Hola '):")
print(f"Original: '{palabra}' | Sin prefijo: '{palabra.removeprefix('Hola ')}'")
print("\n5. Función center(16, '*'):")
print(f"Original: '{palabra}' | Centrado: '{palabra.center(16, '*')}'")