print("Tutorial: Lavar los platos correctamente")
print("Paso 1: Hervir agua")
print("Paso 2: Escoger una esponja adecuada, se utiliza la esponja con dos lados, uno suave y el otro lado texturizado")
print("Paso 3: Escoger un bañador hondo donde se lavará la loza")
print("Paso 4: Escoger un lavavajillas que sea sacagrasa de calidad")
print("Paso 5: Clasificación de loza primer grupo: vasos, platos, cubiertos y todo que no tenga grasa")
print("Paso 6: Clasificación de loza segundo grupo: vasos, platos, cubiertos y utensilios que tenga grasa")
print("Paso 7: Clasificación de loza tercer grupo: ollas")
print("Paso 8: Clasificación de loza cuarto grupo: sartenes")
print("Paso 9: Vaciar el agua hervida al contenedor o bañador donde se lavará la loza")
print("Paso 10: Vacia un poco de lavavajillas a la esponja de lavar loza y lavar el grupo 1 y 2")
print("Paso 11: Desechar el agua, volver a llenar el bañador con nueva agua hervida y caliente")
print("Paso 12: Repetir los pasos 9 y 10 para lavar los grupos 3 y 4 ")
print("Paso 13: Desechar el agua, y enjuaga la loza en el mismo orden de lavado")
print("Paso 14: Dejar secar al aire una hora aproximadamente")
print("Paso 15: Posteriormente con un trapo de secado limpio terminar de secar la loza, es importante seguir respetando el orden de clasificación para el secado también.")
print("Paso 16: Guardar la loza en su respectivo lugar")
print("Paso 17: Lavar el bañador, mesones y esponja")