print("Una dulcería tiene 2 listas una con los productos y otra con los precios")
producto=["Bon Bon Bum", "Oreo", "Chizitos"]
precio=[1.5, 5, 4]
print("Agregar 2 productos nuevos al final de las listas")
producto.extend(["Papas Fritas","Chupete"])
print(producto)
precio.extend([10,1.5])
print(precio)
print("Eliminar el producto con el nombre 'Bon Bon Bum' de las listas")
indice=(producto.index("Bon Bon Bum"))
producto.pop(indice)
precio.pop(indice)
print(producto)
print(precio)
print("¿Cuánto cuesta el producto 'Oreo' y 'Chizitos'?")
indice=(producto.index("Oreo"))
print("El precio de la Chizitos es:", precio[indice])
indice=(producto.index("Chizitos"))
print("El precio de la Oreo es:" , precio[indice])
print("¿Cuál es el producto más caro y el más barato?")
max=(max(precio))
print("El precio más caro es:", max)
min=(min(precio))
print("El precio más barato es:" , min)
print("¿Cuántos productos tienes en total?")
print (len(producto))
print("¿Cuanto cuestan todos los productos?")
print (sum(precio))
print("Ordena los productos y precios del más barato al más caro")
precio_temp = precio.copy()
precio_temp.sort()
producto_ordenado = []
precio_1 = precio_temp[0] 
indice_1 = precio.index(precio_1)
producto_ordenado.append(producto[indice_1])
precio_2 = precio_temp[1] 
indice_2 = precio.index(precio_2)
producto_ordenado.append(producto[indice_2])
precio_3 = precio_temp[2] 
indice_3 = precio.index(precio_3)
producto_ordenado.append(producto[indice_3])
precio_4 = precio_temp[3] 
indice_4 = precio.index(precio_4)
producto_ordenado.append(producto[indice_4])
print("Productos ordenados:", producto_ordenado)
print("Precios ordenados:", precio_temp)
print("Eliminar todos los productos de las listas")
print(producto.clear())
print(precio.clear())